<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuanHuyenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $quanhuyen = array(
            array('maqh' => '001','name' => 'Quận Ba Đình','type' => 'Quận','matp' => '01'),
            array('maqh' => '002','name' => 'Quận Hoàn Kiếm','type' => 'Quận','matp' => '01'),
            array('maqh' => '003','name' => 'Quận Tây Hồ','type' => 'Quận','matp' => '01'),
            array('maqh' => '004','name' => 'Quận Long Biên','type' => 'Quận','matp' => '01'),
            array('maqh' => '005','name' => 'Quận Cầu Giấy','type' => 'Quận','matp' => '01'),
            array('maqh' => '006','name' => 'Quận Đống Đa','type' => 'Quận','matp' => '01'),
            array('maqh' => '007','name' => 'Quận Hai Bà Trưng','type' => 'Quận','matp' => '01'),
            array('maqh' => '008','name' => 'Quận Hoàng Mai','type' => 'Quận','matp' => '01'),
            array('maqh' => '009','name' => 'Quận Thanh Xuân','type' => 'Quận','matp' => '01'),
            array('maqh' => '016','name' => 'Huyện Sóc Sơn','type' => 'Huyện','matp' => '01'),
            array('maqh' => '017','name' => 'Huyện Đông Anh','type' => 'Huyện','matp' => '01'),
            array('maqh' => '018','name' => 'Huyện Gia Lâm','type' => 'Huyện','matp' => '01'),
            array('maqh' => '019','name' => 'Quận Nam Từ Liêm','type' => 'Quận','matp' => '01'),
            array('maqh' => '020','name' => 'Huyện Thanh Trì','type' => 'Huyện','matp' => '01'),
            array('maqh' => '021','name' => 'Quận Bắc Từ Liêm','type' => 'Quận','matp' => '01'),
            array('maqh' => '024','name' => 'Thành phố Hà Giang','type' => 'Thành phố','matp' => '02'),
            array('maqh' => '026','name' => 'Huyện Đồng Văn','type' => 'Huyện','matp' => '02'),
            array('maqh' => '027','name' => 'Huyện Mèo Vạc','type' => 'Huyện','matp' => '02'),
            array('maqh' => '028','name' => 'Huyện Yên Minh','type' => 'Huyện','matp' => '02'),
            array('maqh' => '029','name' => 'Huyện Quản Bạ','type' => 'Huyện','matp' => '02'),
            array('maqh' => '030','name' => 'Huyện Vị Xuyên','type' => 'Huyện','matp' => '02'),
            array('maqh' => '031','name' => 'Huyện Bắc Mê','type' => 'Huyện','matp' => '02'),
            array('maqh' => '032','name' => 'Huyện Hoàng Su Phì','type' => 'Huyện','matp' => '02'),
            array('maqh' => '033','name' => 'Huyện Xín Mần','type' => 'Huyện','matp' => '02'),
            array('maqh' => '034','name' => 'Huyện Bắc Quang','type' => 'Huyện','matp' => '02'),
            array('maqh' => '035','name' => 'Huyện Quang Bình','type' => 'Huyện','matp' => '02'),
            array('maqh' => '040','name' => 'Thành phố Cao Bằng','type' => 'Thành phố','matp' => '04'),
            array('maqh' => '042','name' => 'Huyện Bảo Lâm','type' => 'Huyện','matp' => '04'),
            array('maqh' => '043','name' => 'Huyện Bảo Lạc','type' => 'Huyện','matp' => '04'),
            array('maqh' => '044','name' => 'Huyện Thông Nông','type' => 'Huyện','matp' => '04'),
            array('maqh' => '045','name' => 'Huyện Hà Quảng','type' => 'Huyện','matp' => '04'),
            array('maqh' => '046','name' => 'Huyện Trà Lĩnh','type' => 'Huyện','matp' => '04'),
            array('maqh' => '047','name' => 'Huyện Trùng Khánh','type' => 'Huyện','matp' => '04'),
            array('maqh' => '048','name' => 'Huyện Hạ Lang','type' => 'Huyện','matp' => '04'),
            array('maqh' => '049','name' => 'Huyện Quảng Uyên','type' => 'Huyện','matp' => '04'),
            array('maqh' => '050','name' => 'Huyện Phục Hoà','type' => 'Huyện','matp' => '04'),
            array('maqh' => '051','name' => 'Huyện Hoà An','type' => 'Huyện','matp' => '04'),
            array('maqh' => '052','name' => 'Huyện Nguyên Bình','type' => 'Huyện','matp' => '04'),
            array('maqh' => '053','name' => 'Huyện Thạch An','type' => 'Huyện','matp' => '04'),
            array('maqh' => '058','name' => 'Thành Phố Bắc Kạn','type' => 'Thành phố','matp' => '06'),
            array('maqh' => '060','name' => 'Huyện Pác Nặm','type' => 'Huyện','matp' => '06'),
            array('maqh' => '061','name' => 'Huyện Ba Bể','type' => 'Huyện','matp' => '06'),
            array('maqh' => '062','name' => 'Huyện Ngân Sơn','type' => 'Huyện','matp' => '06'),
            array('maqh' => '063','name' => 'Huyện Bạch Thông','type' => 'Huyện','matp' => '06'),
            array('maqh' => '064','name' => 'Huyện Chợ Đồn','type' => 'Huyện','matp' => '06'),
            array('maqh' => '065','name' => 'Huyện Chợ Mới','type' => 'Huyện','matp' => '06'),
            array('maqh' => '066','name' => 'Huyện Na Rì','type' => 'Huyện','matp' => '06'),
            array('maqh' => '070','name' => 'Thành phố Tuyên Quang','type' => 'Thành phố','matp' => '08'),
            array('maqh' => '071','name' => 'Huyện Lâm Bình','type' => 'Huyện','matp' => '08'),
            array('maqh' => '072','name' => 'Huyện Nà Hang','type' => 'Huyện','matp' => '08'),
            array('maqh' => '073','name' => 'Huyện Chiêm Hóa','type' => 'Huyện','matp' => '08'),
            array('maqh' => '074','name' => 'Huyện Hàm Yên','type' => 'Huyện','matp' => '08'),
            array('maqh' => '075','name' => 'Huyện Yên Sơn','type' => 'Huyện','matp' => '08'),
            array('maqh' => '076','name' => 'Huyện Sơn Dương','type' => 'Huyện','matp' => '08'),
            array('maqh' => '080','name' => 'Thành phố Lào Cai','type' => 'Thành phố','matp' => '10'),
            array('maqh' => '082','name' => 'Huyện Bát Xát','type' => 'Huyện','matp' => '10'),
            array('maqh' => '083','name' => 'Huyện Mường Khương','type' => 'Huyện','matp' => '10'),
            array('maqh' => '084','name' => 'Huyện Si Ma Cai','type' => 'Huyện','matp' => '10'),
            array('maqh' => '085','name' => 'Huyện Bắc Hà','type' => 'Huyện','matp' => '10'),
            array('maqh' => '086','name' => 'Huyện Bảo Thắng','type' => 'Huyện','matp' => '10'),
            array('maqh' => '087','name' => 'Huyện Bảo Yên','type' => 'Huyện','matp' => '10'),
            array('maqh' => '088','name' => 'Huyện Sa Pa','type' => 'Huyện','matp' => '10'),
            array('maqh' => '089','name' => 'Huyện Văn Bàn','type' => 'Huyện','matp' => '10'),
            array('maqh' => '094','name' => 'Thành phố Điện Biên Phủ','type' => 'Thành phố','matp' => '11'),
            array('maqh' => '095','name' => 'Thị Xã Mường Lay','type' => 'Thị xã','matp' => '11'),
            array('maqh' => '096','name' => 'Huyện Mường Nhé','type' => 'Huyện','matp' => '11'),
            array('maqh' => '097','name' => 'Huyện Mường Chà','type' => 'Huyện','matp' => '11'),
            array('maqh' => '098','name' => 'Huyện Tủa Chùa','type' => 'Huyện','matp' => '11'),
            array('maqh' => '099','name' => 'Huyện Tuần Giáo','type' => 'Huyện','matp' => '11'),
            array('maqh' => '100','name' => 'Huyện Điện Biên','type' => 'Huyện','matp' => '11'),
            array('maqh' => '101','name' => 'Huyện Điện Biên Đông','type' => 'Huyện','matp' => '11'),
            array('maqh' => '102','name' => 'Huyện Mường Ảng','type' => 'Huyện','matp' => '11'),
            array('maqh' => '103','name' => 'Huyện Nậm Pồ','type' => 'Huyện','matp' => '11'),
            array('maqh' => '105','name' => 'Thành phố Lai Châu','type' => 'Thành phố','matp' => '12'),
            array('maqh' => '106','name' => 'Huyện Tam Đường','type' => 'Huyện','matp' => '12'),
            array('maqh' => '107','name' => 'Huyện Mường Tè','type' => 'Huyện','matp' => '12'),
            array('maqh' => '108','name' => 'Huyện Sìn Hồ','type' => 'Huyện','matp' => '12'),
            array('maqh' => '109','name' => 'Huyện Phong Thổ','type' => 'Huyện','matp' => '12'),
            array('maqh' => '110','name' => 'Huyện Than Uyên','type' => 'Huyện','matp' => '12'),
            array('maqh' => '111','name' => 'Huyện Tân Uyên','type' => 'Huyện','matp' => '12'),
            array('maqh' => '112','name' => 'Huyện Nậm Nhùn','type' => 'Huyện','matp' => '12'),
            array('maqh' => '116','name' => 'Thành phố Sơn La','type' => 'Thành phố','matp' => '14'),
            array('maqh' => '118','name' => 'Huyện Quỳnh Nhai','type' => 'Huyện','matp' => '14'),
            array('maqh' => '119','name' => 'Huyện Thuận Châu','type' => 'Huyện','matp' => '14'),
            array('maqh' => '120','name' => 'Huyện Mường La','type' => 'Huyện','matp' => '14'),
            array('maqh' => '121','name' => 'Huyện Bắc Yên','type' => 'Huyện','matp' => '14'),
            array('maqh' => '122','name' => 'Huyện Phù Yên','type' => 'Huyện','matp' => '14'),
            array('maqh' => '123','name' => 'Huyện Mộc Châu','type' => 'Huyện','matp' => '14'),
            array('maqh' => '124','name' => 'Huyện Yên Châu','type' => 'Huyện','matp' => '14'),
            array('maqh' => '125','name' => 'Huyện Mai Sơn','type' => 'Huyện','matp' => '14'),
            array('maqh' => '126','name' => 'Huyện Sông Mã','type' => 'Huyện','matp' => '14'),
            array('maqh' => '127','name' => 'Huyện Sốp Cộp','type' => 'Huyện','matp' => '14'),
            array('maqh' => '128','name' => 'Huyện Vân Hồ','type' => 'Huyện','matp' => '14'),
            array('maqh' => '132','name' => 'Thành phố Yên Bái','type' => 'Thành phố','matp' => '15'),
            array('maqh' => '133','name' => 'Thị xã Nghĩa Lộ','type' => 'Thị xã','matp' => '15'),
            array('maqh' => '135','name' => 'Huyện Lục Yên','type' => 'Huyện','matp' => '15'),
            array('maqh' => '136','name' => 'Huyện Văn Yên','type' => 'Huyện','matp' => '15'),
            array('maqh' => '137','name' => 'Huyện Mù Căng Chải','type' => 'Huyện','matp' => '15'),
            array('maqh' => '138','name' => 'Huyện Trấn Yên','type' => 'Huyện','matp' => '15'),
            array('maqh' => '139','name' => 'Huyện Trạm Tấu','type' => 'Huyện','matp' => '15'),
            array('maqh' => '140','name' => 'Huyện Văn Chấn','type' => 'Huyện','matp' => '15'),
            array('maqh' => '141','name' => 'Huyện Yên Bình','type' => 'Huyện','matp' => '15'),
            array('maqh' => '148','name' => 'Thành phố Hòa Bình','type' => 'Thành phố','matp' => '17'),
            array('maqh' => '150','name' => 'Huyện Đà Bắc','type' => 'Huyện','matp' => '17'),
            array('maqh' => '151','name' => 'Huyện Kỳ Sơn','type' => 'Huyện','matp' => '17'),
            array('maqh' => '152','name' => 'Huyện Lương Sơn','type' => 'Huyện','matp' => '17'),
            array('maqh' => '153','name' => 'Huyện Kim Bôi','type' => 'Huyện','matp' => '17'),
            array('maqh' => '154','name' => 'Huyện Cao Phong','type' => 'Huyện','matp' => '17'),
            array('maqh' => '155','name' => 'Huyện Tân Lạc','type' => 'Huyện','matp' => '17'),
            array('maqh' => '156','name' => 'Huyện Mai Châu','type' => 'Huyện','matp' => '17'),
            array('maqh' => '157','name' => 'Huyện Lạc Sơn','type' => 'Huyện','matp' => '17'),
            array('maqh' => '158','name' => 'Huyện Yên Thủy','type' => 'Huyện','matp' => '17'),
            array('maqh' => '159','name' => 'Huyện Lạc Thủy','type' => 'Huyện','matp' => '17'),
            array('maqh' => '164','name' => 'Thành phố Thái Nguyên','type' => 'Thành phố','matp' => '19'),
            array('maqh' => '165','name' => 'Thành phố Sông Công','type' => 'Thành phố','matp' => '19'),
            array('maqh' => '167','name' => 'Huyện Định Hóa','type' => 'Huyện','matp' => '19'),
            array('maqh' => '168','name' => 'Huyện Phú Lương','type' => 'Huyện','matp' => '19'),
            array('maqh' => '169','name' => 'Huyện Đồng Hỷ','type' => 'Huyện','matp' => '19'),
            array('maqh' => '170','name' => 'Huyện Võ Nhai','type' => 'Huyện','matp' => '19'),
            array('maqh' => '171','name' => 'Huyện Đại Từ','type' => 'Huyện','matp' => '19'),
            array('maqh' => '172','name' => 'Thị xã Phổ Yên','type' => 'Thị xã','matp' => '19'),
            array('maqh' => '173','name' => 'Huyện Phú Bình','type' => 'Huyện','matp' => '19'),
            array('maqh' => '178','name' => 'Thành phố Lạng Sơn','type' => 'Thành phố','matp' => '20'),
            array('maqh' => '180','name' => 'Huyện Tràng Định','type' => 'Huyện','matp' => '20'),
            array('maqh' => '181','name' => 'Huyện Bình Gia','type' => 'Huyện','matp' => '20'),
            array('maqh' => '182','name' => 'Huyện Văn Lãng','type' => 'Huyện','matp' => '20'),
            array('maqh' => '183','name' => 'Huyện Cao Lộc','type' => 'Huyện','matp' => '20'),
            array('maqh' => '184','name' => 'Huyện Văn Quan','type' => 'Huyện','matp' => '20'),
            array('maqh' => '185','name' => 'Huyện Bắc Sơn','type' => 'Huyện','matp' => '20'),
            array('maqh' => '186','name' => 'Huyện Hữu Lũng','type' => 'Huyện','matp' => '20'),
            array('maqh' => '187','name' => 'Huyện Chi Lăng','type' => 'Huyện','matp' => '20'),
            array('maqh' => '188','name' => 'Huyện Lộc Bình','type' => 'Huyện','matp' => '20'),
            array('maqh' => '189','name' => 'Huyện Đình Lập','type' => 'Huyện','matp' => '20'),
            array('maqh' => '193','name' => 'Thành phố Hạ Long','type' => 'Thành phố','matp' => '22'),
            array('maqh' => '194','name' => 'Thành phố Móng Cái','type' => 'Thành phố','matp' => '22'),
            array('maqh' => '195','name' => 'Thành phố Cẩm Phả','type' => 'Thành phố','matp' => '22'),
            array('maqh' => '196','name' => 'Thành phố Uông Bí','type' => 'Thành phố','matp' => '22'),
            array('maqh' => '198','name' => 'Huyện Bình Liêu','type' => 'Huyện','matp' => '22'),
            array('maqh' => '199','name' => 'Huyện Tiên Yên','type' => 'Huyện','matp' => '22'),
            array('maqh' => '200','name' => 'Huyện Đầm Hà','type' => 'Huyện','matp' => '22'),
            array('maqh' => '201','name' => 'Huyện Hải Hà','type' => 'Huyện','matp' => '22'),
            array('maqh' => '202','name' => 'Huyện Ba Chẽ','type' => 'Huyện','matp' => '22'),
            array('maqh' => '203','name' => 'Huyện Vân Đồn','type' => 'Huyện','matp' => '22'),
            array('maqh' => '204','name' => 'Huyện Hoành Bồ','type' => 'Huyện','matp' => '22'),
            array('maqh' => '205','name' => 'Thị xã Đông Triều','type' => 'Thị xã','matp' => '22'),
            array('maqh' => '206','name' => 'Thị xã Quảng Yên','type' => 'Thị xã','matp' => '22'),
            array('maqh' => '207','name' => 'Huyện Cô Tô','type' => 'Huyện','matp' => '22'),
            array('maqh' => '213','name' => 'Thành phố Bắc Giang','type' => 'Thành phố','matp' => '24'),
            array('maqh' => '215','name' => 'Huyện Yên Thế','type' => 'Huyện','matp' => '24'),
            array('maqh' => '216','name' => 'Huyện Tân Yên','type' => 'Huyện','matp' => '24'),
            array('maqh' => '217','name' => 'Huyện Lạng Giang','type' => 'Huyện','matp' => '24'),
            array('maqh' => '218','name' => 'Huyện Lục Nam','type' => 'Huyện','matp' => '24'),
            array('maqh' => '219','name' => 'Huyện Lục Ngạn','type' => 'Huyện','matp' => '24'),
            array('maqh' => '220','name' => 'Huyện Sơn Động','type' => 'Huyện','matp' => '24'),
            array('maqh' => '221','name' => 'Huyện Yên Dũng','type' => 'Huyện','matp' => '24'),
            array('maqh' => '222','name' => 'Huyện Việt Yên','type' => 'Huyện','matp' => '24'),
            array('maqh' => '223','name' => 'Huyện Hiệp Hòa','type' => 'Huyện','matp' => '24'),
            array('maqh' => '227','name' => 'Thành phố Việt Trì','type' => 'Thành phố','matp' => '25'),
            array('maqh' => '228','name' => 'Thị xã Phú Thọ','type' => 'Thị xã','matp' => '25'),
            array('maqh' => '230','name' => 'Huyện Đoan Hùng','type' => 'Huyện','matp' => '25'),
            array('maqh' => '231','name' => 'Huyện Hạ Hoà','type' => 'Huyện','matp' => '25'),
            array('maqh' => '232','name' => 'Huyện Thanh Ba','type' => 'Huyện','matp' => '25'),
            array('maqh' => '233','name' => 'Huyện Phù Ninh','type' => 'Huyện','matp' => '25'),
            array('maqh' => '234','name' => 'Huyện Yên Lập','type' => 'Huyện','matp' => '25'),
            array('maqh' => '235','name' => 'Huyện Cẩm Khê','type' => 'Huyện','matp' => '25'),
            array('maqh' => '236','name' => 'Huyện Tam Nông','type' => 'Huyện','matp' => '25'),
            array('maqh' => '237','name' => 'Huyện Lâm Thao','type' => 'Huyện','matp' => '25'),
            array('maqh' => '238','name' => 'Huyện Thanh Sơn','type' => 'Huyện','matp' => '25'),
            array('maqh' => '239','name' => 'Huyện Thanh Thuỷ','type' => 'Huyện','matp' => '25'),
            array('maqh' => '240','name' => 'Huyện Tân Sơn','type' => 'Huyện','matp' => '25'),
            array('maqh' => '243','name' => 'Thành phố Vĩnh Yên','type' => 'Thành phố','matp' => '26'),
            array('maqh' => '244','name' => 'Thị xã Phúc Yên','type' => 'Thị xã','matp' => '26'),
            array('maqh' => '246','name' => 'Huyện Lập Thạch','type' => 'Huyện','matp' => '26'),
            array('maqh' => '247','name' => 'Huyện Tam Dương','type' => 'Huyện','matp' => '26'),
            array('maqh' => '248','name' => 'Huyện Tam Đảo','type' => 'Huyện','matp' => '26'),
            array('maqh' => '249','name' => 'Huyện Bình Xuyên','type' => 'Huyện','matp' => '26'),
            array('maqh' => '250','name' => 'Huyện Mê Linh','type' => 'Huyện','matp' => '01'),
            array('maqh' => '251','name' => 'Huyện Yên Lạc','type' => 'Huyện','matp' => '26'),
            array('maqh' => '252','name' => 'Huyện Vĩnh Tường','type' => 'Huyện','matp' => '26'),
            array('maqh' => '253','name' => 'Huyện Sông Lô','type' => 'Huyện','matp' => '26'),
            array('maqh' => '256','name' => 'Thành phố Bắc Ninh','type' => 'Thành phố','matp' => '27'),
            array('maqh' => '258','name' => 'Huyện Yên Phong','type' => 'Huyện','matp' => '27'),
            array('maqh' => '259','name' => 'Huyện Quế Võ','type' => 'Huyện','matp' => '27'),
            array('maqh' => '260','name' => 'Huyện Tiên Du','type' => 'Huyện','matp' => '27'),
            array('maqh' => '261','name' => 'Thị xã Từ Sơn','type' => 'Thị xã','matp' => '27'),
            array('maqh' => '262','name' => 'Huyện Thuận Thành','type' => 'Huyện','matp' => '27'),
            array('maqh' => '263','name' => 'Huyện Gia Bình','type' => 'Huyện','matp' => '27'),
            array('maqh' => '264','name' => 'Huyện Lương Tài','type' => 'Huyện','matp' => '27'),
            array('maqh' => '268','name' => 'Quận Hà Đông','type' => 'Quận','matp' => '01'),
            array('maqh' => '269','name' => 'Thị xã Sơn Tây','type' => 'Thị xã','matp' => '01'),
            array('maqh' => '271','name' => 'Huyện Ba Vì','type' => 'Huyện','matp' => '01'),
            array('maqh' => '272','name' => 'Huyện Phúc Thọ','type' => 'Huyện','matp' => '01'),
            array('maqh' => '273','name' => 'Huyện Đan Phượng','type' => 'Huyện','matp' => '01'),
            array('maqh' => '274','name' => 'Huyện Hoài Đức','type' => 'Huyện','matp' => '01'),
            array('maqh' => '275','name' => 'Huyện Quốc Oai','type' => 'Huyện','matp' => '01'),
            array('maqh' => '276','name' => 'Huyện Thạch Thất','type' => 'Huyện','matp' => '01'),
            array('maqh' => '277','name' => 'Huyện Chương Mỹ','type' => 'Huyện','matp' => '01'),
            array('maqh' => '278','name' => 'Huyện Thanh Oai','type' => 'Huyện','matp' => '01'),
            array('maqh' => '279','name' => 'Huyện Thường Tín','type' => 'Huyện','matp' => '01'),
            array('maqh' => '280','name' => 'Huyện Phú Xuyên','type' => 'Huyện','matp' => '01'),
            array('maqh' => '281','name' => 'Huyện Ứng Hòa','type' => 'Huyện','matp' => '01'),
            array('maqh' => '282','name' => 'Huyện Mỹ Đức','type' => 'Huyện','matp' => '01'),
            array('maqh' => '288','name' => 'Thành phố Hải Dương','type' => 'Thành phố','matp' => '30'),
            array('maqh' => '290','name' => 'Thị xã Chí Linh','type' => 'Thị xã','matp' => '30'),
            array('maqh' => '291','name' => 'Huyện Nam Sách','type' => 'Huyện','matp' => '30'),
            array('maqh' => '292','name' => 'Huyện Kinh Môn','type' => 'Huyện','matp' => '30'),
            array('maqh' => '293','name' => 'Huyện Kim Thành','type' => 'Huyện','matp' => '30'),
            array('maqh' => '294','name' => 'Huyện Thanh Hà','type' => 'Huyện','matp' => '30'),
            array('maqh' => '295','name' => 'Huyện Cẩm Giàng','type' => 'Huyện','matp' => '30'),
            array('maqh' => '296','name' => 'Huyện Bình Giang','type' => 'Huyện','matp' => '30'),
            array('maqh' => '297','name' => 'Huyện Gia Lộc','type' => 'Huyện','matp' => '30'),
            array('maqh' => '298','name' => 'Huyện Tứ Kỳ','type' => 'Huyện','matp' => '30'),
            array('maqh' => '299','name' => 'Huyện Ninh Giang','type' => 'Huyện','matp' => '30'),
            array('maqh' => '300','name' => 'Huyện Thanh Miện','type' => 'Huyện','matp' => '30'),
            array('maqh' => '303','name' => 'Quận Hồng Bàng','type' => 'Quận','matp' => '31'),
            array('maqh' => '304','name' => 'Quận Ngô Quyền','type' => 'Quận','matp' => '31'),
            array('maqh' => '305','name' => 'Quận Lê Chân','type' => 'Quận','matp' => '31'),
            array('maqh' => '306','name' => 'Quận Hải An','type' => 'Quận','matp' => '31'),
            array('maqh' => '307','name' => 'Quận Kiến An','type' => 'Quận','matp' => '31'),
            array('maqh' => '308','name' => 'Quận Đồ Sơn','type' => 'Quận','matp' => '31'),
            array('maqh' => '309','name' => 'Quận Dương Kinh','type' => 'Quận','matp' => '31'),
            array('maqh' => '311','name' => 'Huyện Thuỷ Nguyên','type' => 'Huyện','matp' => '31'),
            array('maqh' => '312','name' => 'Huyện An Dương','type' => 'Huyện','matp' => '31'),
            array('maqh' => '313','name' => 'Huyện An Lão','type' => 'Huyện','matp' => '31'),
            array('maqh' => '314','name' => 'Huyện Kiến Thuỵ','type' => 'Huyện','matp' => '31'),
            array('maqh' => '315','name' => 'Huyện Tiên Lãng','type' => 'Huyện','matp' => '31'),
            array('maqh' => '316','name' => 'Huyện Vĩnh Bảo','type' => 'Huyện','matp' => '31'),
            array('maqh' => '317','name' => 'Huyện Cát Hải','type' => 'Huyện','matp' => '31'),
            array('maqh' => '318','name' => 'Huyện Bạch Long Vĩ','type' => 'Huyện','matp' => '31'),
            array('maqh' => '323','name' => 'Thành phố Hưng Yên','type' => 'Thành phố','matp' => '33'),
            array('maqh' => '325','name' => 'Huyện Văn Lâm','type' => 'Huyện','matp' => '33'),
            array('maqh' => '326','name' => 'Huyện Văn Giang','type' => 'Huyện','matp' => '33'),
            array('maqh' => '327','name' => 'Huyện Yên Mỹ','type' => 'Huyện','matp' => '33'),
            array('maqh' => '328','name' => 'Huyện Mỹ Hào','type' => 'Huyện','matp' => '33'),
            array('maqh' => '329','name' => 'Huyện Ân Thi','type' => 'Huyện','matp' => '33'),
            array('maqh' => '330','name' => 'Huyện Khoái Châu','type' => 'Huyện','matp' => '33'),
            array('maqh' => '331','name' => 'Huyện Kim Động','type' => 'Huyện','matp' => '33'),
            array('maqh' => '332','name' => 'Huyện Tiên Lữ','type' => 'Huyện','matp' => '33'),
            array('maqh' => '333','name' => 'Huyện Phù Cừ','type' => 'Huyện','matp' => '33'),
            array('maqh' => '336','name' => 'Thành phố Thái Bình','type' => 'Thành phố','matp' => '34'),
            array('maqh' => '338','name' => 'Huyện Quỳnh Phụ','type' => 'Huyện','matp' => '34'),
            array('maqh' => '339','name' => 'Huyện Hưng Hà','type' => 'Huyện','matp' => '34'),
            array('maqh' => '340','name' => 'Huyện Đông Hưng','type' => 'Huyện','matp' => '34'),
            array('maqh' => '341','name' => 'Huyện Thái Thụy','type' => 'Huyện','matp' => '34'),
            array('maqh' => '342','name' => 'Huyện Tiền Hải','type' => 'Huyện','matp' => '34'),
            array('maqh' => '343','name' => 'Huyện Kiến Xương','type' => 'Huyện','matp' => '34'),
            array('maqh' => '344','name' => 'Huyện Vũ Thư','type' => 'Huyện','matp' => '34'),
            array('maqh' => '347','name' => 'Thành phố Phủ Lý','type' => 'Thành phố','matp' => '35'),
            array('maqh' => '349','name' => 'Huyện Duy Tiên','type' => 'Huyện','matp' => '35'),
            array('maqh' => '350','name' => 'Huyện Kim Bảng','type' => 'Huyện','matp' => '35'),
            array('maqh' => '351','name' => 'Huyện Thanh Liêm','type' => 'Huyện','matp' => '35'),
            array('maqh' => '352','name' => 'Huyện Bình Lục','type' => 'Huyện','matp' => '35'),
            array('maqh' => '353','name' => 'Huyện Lý Nhân','type' => 'Huyện','matp' => '35'),
            array('maqh' => '356','name' => 'Thành phố Nam Định','type' => 'Thành phố','matp' => '36'),
            array('maqh' => '358','name' => 'Huyện Mỹ Lộc','type' => 'Huyện','matp' => '36'),
            array('maqh' => '359','name' => 'Huyện Vụ Bản','type' => 'Huyện','matp' => '36'),
            array('maqh' => '360','name' => 'Huyện Ý Yên','type' => 'Huyện','matp' => '36'),
            array('maqh' => '361','name' => 'Huyện Nghĩa Hưng','type' => 'Huyện','matp' => '36'),
            array('maqh' => '362','name' => 'Huyện Nam Trực','type' => 'Huyện','matp' => '36'),
            array('maqh' => '363','name' => 'Huyện Trực Ninh','type' => 'Huyện','matp' => '36'),
            array('maqh' => '364','name' => 'Huyện Xuân Trường','type' => 'Huyện','matp' => '36'),
            array('maqh' => '365','name' => 'Huyện Giao Thủy','type' => 'Huyện','matp' => '36'),
            array('maqh' => '366','name' => 'Huyện Hải Hậu','type' => 'Huyện','matp' => '36'),
            array('maqh' => '369','name' => 'Thành phố Ninh Bình','type' => 'Thành phố','matp' => '37'),
            array('maqh' => '370','name' => 'Thành phố Tam Điệp','type' => 'Thành phố','matp' => '37'),
            array('maqh' => '372','name' => 'Huyện Nho Quan','type' => 'Huyện','matp' => '37'),
            array('maqh' => '373','name' => 'Huyện Gia Viễn','type' => 'Huyện','matp' => '37'),
            array('maqh' => '374','name' => 'Huyện Hoa Lư','type' => 'Huyện','matp' => '37'),
            array('maqh' => '375','name' => 'Huyện Yên Khánh','type' => 'Huyện','matp' => '37'),
            array('maqh' => '376','name' => 'Huyện Kim Sơn','type' => 'Huyện','matp' => '37'),
            array('maqh' => '377','name' => 'Huyện Yên Mô','type' => 'Huyện','matp' => '37'),
            array('maqh' => '380','name' => 'Thành phố Thanh Hóa','type' => 'Thành phố','matp' => '38'),
            array('maqh' => '381','name' => 'Thị xã Bỉm Sơn','type' => 'Thị xã','matp' => '38'),
            array('maqh' => '382','name' => 'Thị xã Sầm Sơn','type' => 'Thị xã','matp' => '38'),
            array('maqh' => '384','name' => 'Huyện Mường Lát','type' => 'Huyện','matp' => '38'),
            array('maqh' => '385','name' => 'Huyện Quan Hóa','type' => 'Huyện','matp' => '38'),
            array('maqh' => '386','name' => 'Huyện Bá Thước','type' => 'Huyện','matp' => '38'),
            array('maqh' => '387','name' => 'Huyện Quan Sơn','type' => 'Huyện','matp' => '38'),
            array('maqh' => '388','name' => 'Huyện Lang Chánh','type' => 'Huyện','matp' => '38'),
            array('maqh' => '389','name' => 'Huyện Ngọc Lặc','type' => 'Huyện','matp' => '38'),
            array('maqh' => '390','name' => 'Huyện Cẩm Thủy','type' => 'Huyện','matp' => '38'),
            array('maqh' => '391','name' => 'Huyện Thạch Thành','type' => 'Huyện','matp' => '38'),
            array('maqh' => '392','name' => 'Huyện Hà Trung','type' => 'Huyện','matp' => '38'),
            array('maqh' => '393','name' => 'Huyện Vĩnh Lộc','type' => 'Huyện','matp' => '38'),
            array('maqh' => '394','name' => 'Huyện Yên Định','type' => 'Huyện','matp' => '38'),
            array('maqh' => '395','name' => 'Huyện Thọ Xuân','type' => 'Huyện','matp' => '38'),
            array('maqh' => '396','name' => 'Huyện Thường Xuân','type' => 'Huyện','matp' => '38'),
            array('maqh' => '397','name' => 'Huyện Triệu Sơn','type' => 'Huyện','matp' => '38'),
            array('maqh' => '398','name' => 'Huyện Thiệu Hóa','type' => 'Huyện','matp' => '38'),
            array('maqh' => '399','name' => 'Huyện Hoằng Hóa','type' => 'Huyện','matp' => '38'),
            array('maqh' => '400','name' => 'Huyện Hậu Lộc','type' => 'Huyện','matp' => '38'),
            array('maqh' => '401','name' => 'Huyện Nga Sơn','type' => 'Huyện','matp' => '38'),
            array('maqh' => '402','name' => 'Huyện Như Xuân','type' => 'Huyện','matp' => '38'),
            array('maqh' => '403','name' => 'Huyện Như Thanh','type' => 'Huyện','matp' => '38'),
            array('maqh' => '404','name' => 'Huyện Nông Cống','type' => 'Huyện','matp' => '38'),
            array('maqh' => '405','name' => 'Huyện Đông Sơn','type' => 'Huyện','matp' => '38'),
            array('maqh' => '406','name' => 'Huyện Quảng Xương','type' => 'Huyện','matp' => '38'),
            array('maqh' => '407','name' => 'Huyện Tĩnh Gia','type' => 'Huyện','matp' => '38'),
            array('maqh' => '412','name' => 'Thành phố Vinh','type' => 'Thành phố','matp' => '40'),
            array('maqh' => '413','name' => 'Thị xã Cửa Lò','type' => 'Thị xã','matp' => '40'),
            array('maqh' => '414','name' => 'Thị xã Thái Hoà','type' => 'Thị xã','matp' => '40'),
            array('maqh' => '415','name' => 'Huyện Quế Phong','type' => 'Huyện','matp' => '40'),
            array('maqh' => '416','name' => 'Huyện Quỳ Châu','type' => 'Huyện','matp' => '40'),
            array('maqh' => '417','name' => 'Huyện Kỳ Sơn','type' => 'Huyện','matp' => '40'),
            array('maqh' => '418','name' => 'Huyện Tương Dương','type' => 'Huyện','matp' => '40'),
            array('maqh' => '419','name' => 'Huyện Nghĩa Đàn','type' => 'Huyện','matp' => '40'),
            array('maqh' => '420','name' => 'Huyện Quỳ Hợp','type' => 'Huyện','matp' => '40'),
            array('maqh' => '421','name' => 'Huyện Quỳnh Lưu','type' => 'Huyện','matp' => '40'),
            array('maqh' => '422','name' => 'Huyện Con Cuông','type' => 'Huyện','matp' => '40'),
            array('maqh' => '423','name' => 'Huyện Tân Kỳ','type' => 'Huyện','matp' => '40'),
            array('maqh' => '424','name' => 'Huyện Anh Sơn','type' => 'Huyện','matp' => '40'),
            array('maqh' => '425','name' => 'Huyện Diễn Châu','type' => 'Huyện','matp' => '40'),
            array('maqh' => '426','name' => 'Huyện Yên Thành','type' => 'Huyện','matp' => '40'),
            array('maqh' => '427','name' => 'Huyện Đô Lương','type' => 'Huyện','matp' => '40'),
            array('maqh' => '428','name' => 'Huyện Thanh Chương','type' => 'Huyện','matp' => '40'),
            array('maqh' => '429','name' => 'Huyện Nghi Lộc','type' => 'Huyện','matp' => '40'),
            array('maqh' => '430','name' => 'Huyện Nam Đàn','type' => 'Huyện','matp' => '40'),
            array('maqh' => '431','name' => 'Huyện Hưng Nguyên','type' => 'Huyện','matp' => '40'),
            array('maqh' => '432','name' => 'Thị xã Hoàng Mai','type' => 'Thị xã','matp' => '40'),
            array('maqh' => '436','name' => 'Thành phố Hà Tĩnh','type' => 'Thành phố','matp' => '42'),
            array('maqh' => '437','name' => 'Thị xã Hồng Lĩnh','type' => 'Thị xã','matp' => '42'),
            array('maqh' => '439','name' => 'Huyện Hương Sơn','type' => 'Huyện','matp' => '42'),
            array('maqh' => '440','name' => 'Huyện Đức Thọ','type' => 'Huyện','matp' => '42'),
            array('maqh' => '441','name' => 'Huyện Vũ Quang','type' => 'Huyện','matp' => '42'),
            array('maqh' => '442','name' => 'Huyện Nghi Xuân','type' => 'Huyện','matp' => '42'),
            array('maqh' => '443','name' => 'Huyện Can Lộc','type' => 'Huyện','matp' => '42'),
            array('maqh' => '444','name' => 'Huyện Hương Khê','type' => 'Huyện','matp' => '42'),
            array('maqh' => '445','name' => 'Huyện Thạch Hà','type' => 'Huyện','matp' => '42'),
            array('maqh' => '446','name' => 'Huyện Cẩm Xuyên','type' => 'Huyện','matp' => '42'),
            array('maqh' => '447','name' => 'Huyện Kỳ Anh','type' => 'Huyện','matp' => '42'),
            array('maqh' => '448','name' => 'Huyện Lộc Hà','type' => 'Huyện','matp' => '42'),
            array('maqh' => '449','name' => 'Thị xã Kỳ Anh','type' => 'Thị xã','matp' => '42'),
            array('maqh' => '450','name' => 'Thành Phố Đồng Hới','type' => 'Thành phố','matp' => '44'),
            array('maqh' => '452','name' => 'Huyện Minh Hóa','type' => 'Huyện','matp' => '44'),
            array('maqh' => '453','name' => 'Huyện Tuyên Hóa','type' => 'Huyện','matp' => '44'),
            array('maqh' => '454','name' => 'Huyện Quảng Trạch','type' => 'Thị xã','matp' => '44'),
            array('maqh' => '455','name' => 'Huyện Bố Trạch','type' => 'Huyện','matp' => '44'),
            array('maqh' => '456','name' => 'Huyện Quảng Ninh','type' => 'Huyện','matp' => '44'),
            array('maqh' => '457','name' => 'Huyện Lệ Thủy','type' => 'Huyện','matp' => '44'),
            array('maqh' => '458','name' => 'Thị xã Ba Đồn','type' => 'Huyện','matp' => '44'),
            array('maqh' => '461','name' => 'Thành phố Đông Hà','type' => 'Thành phố','matp' => '45'),
            array('maqh' => '462','name' => 'Thị xã Quảng Trị','type' => 'Thị xã','matp' => '45'),
            array('maqh' => '464','name' => 'Huyện Vĩnh Linh','type' => 'Huyện','matp' => '45'),
            array('maqh' => '465','name' => 'Huyện Hướng Hóa','type' => 'Huyện','matp' => '45'),
            array('maqh' => '466','name' => 'Huyện Gio Linh','type' => 'Huyện','matp' => '45'),
            array('maqh' => '467','name' => 'Huyện Đa Krông','type' => 'Huyện','matp' => '45'),
            array('maqh' => '468','name' => 'Huyện Cam Lộ','type' => 'Huyện','matp' => '45'),
            array('maqh' => '469','name' => 'Huyện Triệu Phong','type' => 'Huyện','matp' => '45'),
            array('maqh' => '470','name' => 'Huyện Hải Lăng','type' => 'Huyện','matp' => '45'),
            array('maqh' => '471','name' => 'Huyện Cồn Cỏ','type' => 'Huyện','matp' => '45'),
            array('maqh' => '474','name' => 'Thành phố Huế','type' => 'Thành phố','matp' => '46'),
            array('maqh' => '476','name' => 'Huyện Phong Điền','type' => 'Huyện','matp' => '46'),
            array('maqh' => '477','name' => 'Huyện Quảng Điền','type' => 'Huyện','matp' => '46'),
            array('maqh' => '478','name' => 'Huyện Phú Vang','type' => 'Huyện','matp' => '46'),
            array('maqh' => '479','name' => 'Thị xã Hương Thủy','type' => 'Thị xã','matp' => '46'),
            array('maqh' => '480','name' => 'Thị xã Hương Trà','type' => 'Thị xã','matp' => '46'),
            array('maqh' => '481','name' => 'Huyện A Lưới','type' => 'Huyện','matp' => '46'),
            array('maqh' => '482','name' => 'Huyện Phú Lộc','type' => 'Huyện','matp' => '46'),
            array('maqh' => '483','name' => 'Huyện Nam Đông','type' => 'Huyện','matp' => '46'),
            array('maqh' => '490','name' => 'Quận Liên Chiểu','type' => 'Quận','matp' => '48'),
            array('maqh' => '491','name' => 'Quận Thanh Khê','type' => 'Quận','matp' => '48'),
            array('maqh' => '492','name' => 'Quận Hải Châu','type' => 'Quận','matp' => '48'),
            array('maqh' => '493','name' => 'Quận Sơn Trà','type' => 'Quận','matp' => '48'),
            array('maqh' => '494','name' => 'Quận Ngũ Hành Sơn','type' => 'Quận','matp' => '48'),
            array('maqh' => '495','name' => 'Quận Cẩm Lệ','type' => 'Quận','matp' => '48'),
            array('maqh' => '497','name' => 'Huyện Hòa Vang','type' => 'Huyện','matp' => '48'),
            array('maqh' => '498','name' => 'Huyện Hoàng Sa','type' => 'Huyện','matp' => '48'),
            array('maqh' => '502','name' => 'Thành phố Tam Kỳ','type' => 'Thành phố','matp' => '49'),
            array('maqh' => '503','name' => 'Thành phố Hội An','type' => 'Thành phố','matp' => '49'),
            array('maqh' => '504','name' => 'Huyện Tây Giang','type' => 'Huyện','matp' => '49'),
            array('maqh' => '505','name' => 'Huyện Đông Giang','type' => 'Huyện','matp' => '49'),
            array('maqh' => '506','name' => 'Huyện Đại Lộc','type' => 'Huyện','matp' => '49'),
            array('maqh' => '507','name' => 'Thị xã Điện Bàn','type' => 'Thị xã','matp' => '49'),
            array('maqh' => '508','name' => 'Huyện Duy Xuyên','type' => 'Huyện','matp' => '49'),
            array('maqh' => '509','name' => 'Huyện Quế Sơn','type' => 'Huyện','matp' => '49'),
            array('maqh' => '510','name' => 'Huyện Nam Giang','type' => 'Huyện','matp' => '49'),
            array('maqh' => '511','name' => 'Huyện Phước Sơn','type' => 'Huyện','matp' => '49'),
            array('maqh' => '512','name' => 'Huyện Hiệp Đức','type' => 'Huyện','matp' => '49'),
            array('maqh' => '513','name' => 'Huyện Thăng Bình','type' => 'Huyện','matp' => '49'),
            array('maqh' => '514','name' => 'Huyện Tiên Phước','type' => 'Huyện','matp' => '49'),
            array('maqh' => '515','name' => 'Huyện Bắc Trà My','type' => 'Huyện','matp' => '49'),
            array('maqh' => '516','name' => 'Huyện Nam Trà My','type' => 'Huyện','matp' => '49'),
            array('maqh' => '517','name' => 'Huyện Núi Thành','type' => 'Huyện','matp' => '49'),
            array('maqh' => '518','name' => 'Huyện Phú Ninh','type' => 'Huyện','matp' => '49'),
            array('maqh' => '519','name' => 'Huyện Nông Sơn','type' => 'Huyện','matp' => '49'),
            array('maqh' => '522','name' => 'Thành phố Quảng Ngãi','type' => 'Thành phố','matp' => '51'),
            array('maqh' => '524','name' => 'Huyện Bình Sơn','type' => 'Huyện','matp' => '51'),
            array('maqh' => '525','name' => 'Huyện Trà Bồng','type' => 'Huyện','matp' => '51'),
            array('maqh' => '526','name' => 'Huyện Tây Trà','type' => 'Huyện','matp' => '51'),
            array('maqh' => '527','name' => 'Huyện Sơn Tịnh','type' => 'Huyện','matp' => '51'),
            array('maqh' => '528','name' => 'Huyện Tư Nghĩa','type' => 'Huyện','matp' => '51'),
            array('maqh' => '529','name' => 'Huyện Sơn Hà','type' => 'Huyện','matp' => '51'),
            array('maqh' => '530','name' => 'Huyện Sơn Tây','type' => 'Huyện','matp' => '51'),
            array('maqh' => '531','name' => 'Huyện Minh Long','type' => 'Huyện','matp' => '51'),
            array('maqh' => '532','name' => 'Huyện Nghĩa Hành','type' => 'Huyện','matp' => '51'),
            array('maqh' => '533','name' => 'Huyện Mộ Đức','type' => 'Huyện','matp' => '51'),
            array('maqh' => '534','name' => 'Huyện Đức Phổ','type' => 'Huyện','matp' => '51'),
            array('maqh' => '535','name' => 'Huyện Ba Tơ','type' => 'Huyện','matp' => '51'),
            array('maqh' => '536','name' => 'Huyện Lý Sơn','type' => 'Huyện','matp' => '51'),
            array('maqh' => '540','name' => 'Thành phố Qui Nhơn','type' => 'Thành phố','matp' => '52'),
            array('maqh' => '542','name' => 'Huyện An Lão','type' => 'Huyện','matp' => '52'),
            array('maqh' => '543','name' => 'Huyện Hoài Nhơn','type' => 'Huyện','matp' => '52'),
            array('maqh' => '544','name' => 'Huyện Hoài Ân','type' => 'Huyện','matp' => '52'),
            array('maqh' => '545','name' => 'Huyện Phù Mỹ','type' => 'Huyện','matp' => '52'),
            array('maqh' => '546','name' => 'Huyện Vĩnh Thạnh','type' => 'Huyện','matp' => '52'),
            array('maqh' => '547','name' => 'Huyện Tây Sơn','type' => 'Huyện','matp' => '52'),
            array('maqh' => '548','name' => 'Huyện Phù Cát','type' => 'Huyện','matp' => '52'),
            array('maqh' => '549','name' => 'Thị xã An Nhơn','type' => 'Thị xã','matp' => '52'),
            array('maqh' => '550','name' => 'Huyện Tuy Phước','type' => 'Huyện','matp' => '52'),
            array('maqh' => '551','name' => 'Huyện Vân Canh','type' => 'Huyện','matp' => '52'),
            array('maqh' => '555','name' => 'Thành phố Tuy Hoà','type' => 'Thành phố','matp' => '54'),
            array('maqh' => '557','name' => 'Thị xã Sông Cầu','type' => 'Thị xã','matp' => '54'),
            array('maqh' => '558','name' => 'Huyện Đồng Xuân','type' => 'Huyện','matp' => '54'),
            array('maqh' => '559','name' => 'Huyện Tuy An','type' => 'Huyện','matp' => '54'),
            array('maqh' => '560','name' => 'Huyện Sơn Hòa','type' => 'Huyện','matp' => '54'),
            array('maqh' => '561','name' => 'Huyện Sông Hinh','type' => 'Huyện','matp' => '54'),
            array('maqh' => '562','name' => 'Huyện Tây Hoà','type' => 'Huyện','matp' => '54'),
            array('maqh' => '563','name' => 'Huyện Phú Hoà','type' => 'Huyện','matp' => '54'),
            array('maqh' => '564','name' => 'Huyện Đông Hòa','type' => 'Huyện','matp' => '54'),
            array('maqh' => '568','name' => 'Thành phố Nha Trang','type' => 'Thành phố','matp' => '56'),
            array('maqh' => '569','name' => 'Thành phố Cam Ranh','type' => 'Thành phố','matp' => '56'),
            array('maqh' => '570','name' => 'Huyện Cam Lâm','type' => 'Huyện','matp' => '56'),
            array('maqh' => '571','name' => 'Huyện Vạn Ninh','type' => 'Huyện','matp' => '56'),
            array('maqh' => '572','name' => 'Thị xã Ninh Hòa','type' => 'Thị xã','matp' => '56'),
            array('maqh' => '573','name' => 'Huyện Khánh Vĩnh','type' => 'Huyện','matp' => '56'),
            array('maqh' => '574','name' => 'Huyện Diên Khánh','type' => 'Huyện','matp' => '56'),
            array('maqh' => '575','name' => 'Huyện Khánh Sơn','type' => 'Huyện','matp' => '56'),
            array('maqh' => '576','name' => 'Huyện Trường Sa','type' => 'Huyện','matp' => '56'),
            array('maqh' => '582','name' => 'Thành phố Phan Rang-Tháp Chàm','type' => 'Thành phố','matp' => '58'),
            array('maqh' => '584','name' => 'Huyện Bác Ái','type' => 'Huyện','matp' => '58'),
            array('maqh' => '585','name' => 'Huyện Ninh Sơn','type' => 'Huyện','matp' => '58'),
            array('maqh' => '586','name' => 'Huyện Ninh Hải','type' => 'Huyện','matp' => '58'),
            array('maqh' => '587','name' => 'Huyện Ninh Phước','type' => 'Huyện','matp' => '58'),
            array('maqh' => '588','name' => 'Huyện Thuận Bắc','type' => 'Huyện','matp' => '58'),
            array('maqh' => '589','name' => 'Huyện Thuận Nam','type' => 'Huyện','matp' => '58'),
            array('maqh' => '593','name' => 'Thành phố Phan Thiết','type' => 'Thành phố','matp' => '60'),
            array('maqh' => '594','name' => 'Thị xã La Gi','type' => 'Thị xã','matp' => '60'),
            array('maqh' => '595','name' => 'Huyện Tuy Phong','type' => 'Huyện','matp' => '60'),
            array('maqh' => '596','name' => 'Huyện Bắc Bình','type' => 'Huyện','matp' => '60'),
            array('maqh' => '597','name' => 'Huyện Hàm Thuận Bắc','type' => 'Huyện','matp' => '60'),
            array('maqh' => '598','name' => 'Huyện Hàm Thuận Nam','type' => 'Huyện','matp' => '60'),
            array('maqh' => '599','name' => 'Huyện Tánh Linh','type' => 'Huyện','matp' => '60'),
            array('maqh' => '600','name' => 'Huyện Đức Linh','type' => 'Huyện','matp' => '60'),
            array('maqh' => '601','name' => 'Huyện Hàm Tân','type' => 'Huyện','matp' => '60'),
            array('maqh' => '602','name' => 'Huyện Phú Quí','type' => 'Huyện','matp' => '60'),
            array('maqh' => '608','name' => 'Thành phố Kon Tum','type' => 'Thành phố','matp' => '62'),
            array('maqh' => '610','name' => 'Huyện Đắk Glei','type' => 'Huyện','matp' => '62'),
            array('maqh' => '611','name' => 'Huyện Ngọc Hồi','type' => 'Huyện','matp' => '62'),
            array('maqh' => '612','name' => 'Huyện Đắk Tô','type' => 'Huyện','matp' => '62'),
            array('maqh' => '613','name' => 'Huyện Kon Plông','type' => 'Huyện','matp' => '62'),
            array('maqh' => '614','name' => 'Huyện Kon Rẫy','type' => 'Huyện','matp' => '62'),
            array('maqh' => '615','name' => 'Huyện Đắk Hà','type' => 'Huyện','matp' => '62'),
            array('maqh' => '616','name' => 'Huyện Sa Thầy','type' => 'Huyện','matp' => '62'),
            array('maqh' => '617','name' => 'Huyện Tu Mơ Rông','type' => 'Huyện','matp' => '62'),
            array('maqh' => '618','name' => 'Huyện Ia H\' Drai','type' => 'Huyện','matp' => '62'),
            array('maqh' => '622','name' => 'Thành phố Pleiku','type' => 'Thành phố','matp' => '64'),
            array('maqh' => '623','name' => 'Thị xã An Khê','type' => 'Thị xã','matp' => '64'),
            array('maqh' => '624','name' => 'Thị xã Ayun Pa','type' => 'Thị xã','matp' => '64'),
            array('maqh' => '625','name' => 'Huyện KBang','type' => 'Huyện','matp' => '64'),
            array('maqh' => '626','name' => 'Huyện Đăk Đoa','type' => 'Huyện','matp' => '64'),
            array('maqh' => '627','name' => 'Huyện Chư Păh','type' => 'Huyện','matp' => '64'),
            array('maqh' => '628','name' => 'Huyện Ia Grai','type' => 'Huyện','matp' => '64'),
            array('maqh' => '629','name' => 'Huyện Mang Yang','type' => 'Huyện','matp' => '64'),
            array('maqh' => '630','name' => 'Huyện Kông Chro','type' => 'Huyện','matp' => '64'),
            array('maqh' => '631','name' => 'Huyện Đức Cơ','type' => 'Huyện','matp' => '64'),
            array('maqh' => '632','name' => 'Huyện Chư Prông','type' => 'Huyện','matp' => '64'),
            array('maqh' => '633','name' => 'Huyện Chư Sê','type' => 'Huyện','matp' => '64'),
            array('maqh' => '634','name' => 'Huyện Đăk Pơ','type' => 'Huyện','matp' => '64'),
            array('maqh' => '635','name' => 'Huyện Ia Pa','type' => 'Huyện','matp' => '64'),
            array('maqh' => '637','name' => 'Huyện Krông Pa','type' => 'Huyện','matp' => '64'),
            array('maqh' => '638','name' => 'Huyện Phú Thiện','type' => 'Huyện','matp' => '64'),
            array('maqh' => '639','name' => 'Huyện Chư Pưh','type' => 'Huyện','matp' => '64'),
            array('maqh' => '643','name' => 'Thành phố Buôn Ma Thuột','type' => 'Thành phố','matp' => '66'),
            array('maqh' => '644','name' => 'Thị Xã Buôn Hồ','type' => 'Thị xã','matp' => '66'),
            array('maqh' => '645','name' => 'Huyện Ea H\'leo','type' => 'Huyện','matp' => '66'),
            array('maqh' => '646','name' => 'Huyện Ea Súp','type' => 'Huyện','matp' => '66'),
            array('maqh' => '647','name' => 'Huyện Buôn Đôn','type' => 'Huyện','matp' => '66'),
            array('maqh' => '648','name' => 'Huyện Cư M\'gar','type' => 'Huyện','matp' => '66'),
            array('maqh' => '649','name' => 'Huyện Krông Búk','type' => 'Huyện','matp' => '66'),
            array('maqh' => '650','name' => 'Huyện Krông Năng','type' => 'Huyện','matp' => '66'),
            array('maqh' => '651','name' => 'Huyện Ea Kar','type' => 'Huyện','matp' => '66'),
            array('maqh' => '652','name' => 'Huyện M\'Đrắk','type' => 'Huyện','matp' => '66'),
            array('maqh' => '653','name' => 'Huyện Krông Bông','type' => 'Huyện','matp' => '66'),
            array('maqh' => '654','name' => 'Huyện Krông Pắc','type' => 'Huyện','matp' => '66'),
            array('maqh' => '655','name' => 'Huyện Krông A Na','type' => 'Huyện','matp' => '66'),
            array('maqh' => '656','name' => 'Huyện Lắk','type' => 'Huyện','matp' => '66'),
            array('maqh' => '657','name' => 'Huyện Cư Kuin','type' => 'Huyện','matp' => '66'),
            array('maqh' => '660','name' => 'Thị xã Gia Nghĩa','type' => 'Thị xã','matp' => '67'),
            array('maqh' => '661','name' => 'Huyện Đăk Glong','type' => 'Huyện','matp' => '67'),
            array('maqh' => '662','name' => 'Huyện Cư Jút','type' => 'Huyện','matp' => '67'),
            array('maqh' => '663','name' => 'Huyện Đắk Mil','type' => 'Huyện','matp' => '67'),
            array('maqh' => '664','name' => 'Huyện Krông Nô','type' => 'Huyện','matp' => '67'),
            array('maqh' => '665','name' => 'Huyện Đắk Song','type' => 'Huyện','matp' => '67'),
            array('maqh' => '666','name' => 'Huyện Đắk R\'Lấp','type' => 'Huyện','matp' => '67'),
            array('maqh' => '667','name' => 'Huyện Tuy Đức','type' => 'Huyện','matp' => '67'),
            array('maqh' => '672','name' => 'Thành phố Đà Lạt','type' => 'Thành phố','matp' => '68'),
            array('maqh' => '673','name' => 'Thành phố Bảo Lộc','type' => 'Thành phố','matp' => '68'),
            array('maqh' => '674','name' => 'Huyện Đam Rông','type' => 'Huyện','matp' => '68'),
            array('maqh' => '675','name' => 'Huyện Lạc Dương','type' => 'Huyện','matp' => '68'),
            array('maqh' => '676','name' => 'Huyện Lâm Hà','type' => 'Huyện','matp' => '68'),
            array('maqh' => '677','name' => 'Huyện Đơn Dương','type' => 'Huyện','matp' => '68'),
            array('maqh' => '678','name' => 'Huyện Đức Trọng','type' => 'Huyện','matp' => '68'),
            array('maqh' => '679','name' => 'Huyện Di Linh','type' => 'Huyện','matp' => '68'),
            array('maqh' => '680','name' => 'Huyện Bảo Lâm','type' => 'Huyện','matp' => '68'),
            array('maqh' => '681','name' => 'Huyện Đạ Huoai','type' => 'Huyện','matp' => '68'),
            array('maqh' => '682','name' => 'Huyện Đạ Tẻh','type' => 'Huyện','matp' => '68'),
            array('maqh' => '683','name' => 'Huyện Cát Tiên','type' => 'Huyện','matp' => '68'),
            array('maqh' => '688','name' => 'Thị xã Phước Long','type' => 'Thị xã','matp' => '70'),
            array('maqh' => '689','name' => 'Thị xã Đồng Xoài','type' => 'Thị xã','matp' => '70'),
            array('maqh' => '690','name' => 'Thị xã Bình Long','type' => 'Thị xã','matp' => '70'),
            array('maqh' => '691','name' => 'Huyện Bù Gia Mập','type' => 'Huyện','matp' => '70'),
            array('maqh' => '692','name' => 'Huyện Lộc Ninh','type' => 'Huyện','matp' => '70'),
            array('maqh' => '693','name' => 'Huyện Bù Đốp','type' => 'Huyện','matp' => '70'),
            array('maqh' => '694','name' => 'Huyện Hớn Quản','type' => 'Huyện','matp' => '70'),
            array('maqh' => '695','name' => 'Huyện Đồng Phú','type' => 'Huyện','matp' => '70'),
            array('maqh' => '696','name' => 'Huyện Bù Đăng','type' => 'Huyện','matp' => '70'),
            array('maqh' => '697','name' => 'Huyện Chơn Thành','type' => 'Huyện','matp' => '70'),
            array('maqh' => '698','name' => 'Huyện Phú Riềng','type' => 'Huyện','matp' => '70'),
            array('maqh' => '703','name' => 'Thành phố Tây Ninh','type' => 'Thành phố','matp' => '72'),
            array('maqh' => '705','name' => 'Huyện Tân Biên','type' => 'Huyện','matp' => '72'),
            array('maqh' => '706','name' => 'Huyện Tân Châu','type' => 'Huyện','matp' => '72'),
            array('maqh' => '707','name' => 'Huyện Dương Minh Châu','type' => 'Huyện','matp' => '72'),
            array('maqh' => '708','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '72'),
            array('maqh' => '709','name' => 'Huyện Hòa Thành','type' => 'Huyện','matp' => '72'),
            array('maqh' => '710','name' => 'Huyện Gò Dầu','type' => 'Huyện','matp' => '72'),
            array('maqh' => '711','name' => 'Huyện Bến Cầu','type' => 'Huyện','matp' => '72'),
            array('maqh' => '712','name' => 'Huyện Trảng Bàng','type' => 'Huyện','matp' => '72'),
            array('maqh' => '718','name' => 'Thành phố Thủ Dầu Một','type' => 'Thành phố','matp' => '74'),
            array('maqh' => '719','name' => 'Huyện Bàu Bàng','type' => 'Huyện','matp' => '74'),
            array('maqh' => '720','name' => 'Huyện Dầu Tiếng','type' => 'Huyện','matp' => '74'),
            array('maqh' => '721','name' => 'Thị xã Bến Cát','type' => 'Thị xã','matp' => '74'),
            array('maqh' => '722','name' => 'Huyện Phú Giáo','type' => 'Huyện','matp' => '74'),
            array('maqh' => '723','name' => 'Thị xã Tân Uyên','type' => 'Thị xã','matp' => '74'),
            array('maqh' => '724','name' => 'Thị xã Dĩ An','type' => 'Thị xã','matp' => '74'),
            array('maqh' => '725','name' => 'Thị xã Thuận An','type' => 'Thị xã','matp' => '74'),
            array('maqh' => '726','name' => 'Huyện Bắc Tân Uyên','type' => 'Huyện','matp' => '74'),
            array('maqh' => '731','name' => 'Thành phố Biên Hòa','type' => 'Thành phố','matp' => '75'),
            array('maqh' => '732','name' => 'Thị xã Long Khánh','type' => 'Thị xã','matp' => '75'),
            array('maqh' => '734','name' => 'Huyện Tân Phú','type' => 'Huyện','matp' => '75'),
            array('maqh' => '735','name' => 'Huyện Vĩnh Cửu','type' => 'Huyện','matp' => '75'),
            array('maqh' => '736','name' => 'Huyện Định Quán','type' => 'Huyện','matp' => '75'),
            array('maqh' => '737','name' => 'Huyện Trảng Bom','type' => 'Huyện','matp' => '75'),
            array('maqh' => '738','name' => 'Huyện Thống Nhất','type' => 'Huyện','matp' => '75'),
            array('maqh' => '739','name' => 'Huyện Cẩm Mỹ','type' => 'Huyện','matp' => '75'),
            array('maqh' => '740','name' => 'Huyện Long Thành','type' => 'Huyện','matp' => '75'),
            array('maqh' => '741','name' => 'Huyện Xuân Lộc','type' => 'Huyện','matp' => '75'),
            array('maqh' => '742','name' => 'Huyện Nhơn Trạch','type' => 'Huyện','matp' => '75'),
            array('maqh' => '747','name' => 'Thành phố Vũng Tàu','type' => 'Thành phố','matp' => '77'),
            array('maqh' => '748','name' => 'Thành phố Bà Rịa','type' => 'Thành phố','matp' => '77'),
            array('maqh' => '750','name' => 'Huyện Châu Đức','type' => 'Huyện','matp' => '77'),
            array('maqh' => '751','name' => 'Huyện Xuyên Mộc','type' => 'Huyện','matp' => '77'),
            array('maqh' => '752','name' => 'Huyện Long Điền','type' => 'Huyện','matp' => '77'),
            array('maqh' => '753','name' => 'Huyện Đất Đỏ','type' => 'Huyện','matp' => '77'),
            array('maqh' => '754','name' => 'Huyện Tân Thành','type' => 'Huyện','matp' => '77'),
            array('maqh' => '755','name' => 'Huyện Côn Đảo','type' => 'Huyện','matp' => '77'),
            array('maqh' => '760','name' => 'Quận 1','type' => 'Quận','matp' => '79'),
            array('maqh' => '761','name' => 'Quận 12','type' => 'Quận','matp' => '79'),
            array('maqh' => '762','name' => 'Quận Thủ Đức','type' => 'Quận','matp' => '79'),
            array('maqh' => '763','name' => 'Quận 9','type' => 'Quận','matp' => '79'),
            array('maqh' => '764','name' => 'Quận Gò Vấp','type' => 'Quận','matp' => '79'),
            array('maqh' => '765','name' => 'Quận Bình Thạnh','type' => 'Quận','matp' => '79'),
            array('maqh' => '766','name' => 'Quận Tân Bình','type' => 'Quận','matp' => '79'),
            array('maqh' => '767','name' => 'Quận Tân Phú','type' => 'Quận','matp' => '79'),
            array('maqh' => '768','name' => 'Quận Phú Nhuận','type' => 'Quận','matp' => '79'),
            array('maqh' => '769','name' => 'Quận 2','type' => 'Quận','matp' => '79'),
            array('maqh' => '770','name' => 'Quận 3','type' => 'Quận','matp' => '79'),
            array('maqh' => '771','name' => 'Quận 10','type' => 'Quận','matp' => '79'),
            array('maqh' => '772','name' => 'Quận 11','type' => 'Quận','matp' => '79'),
            array('maqh' => '773','name' => 'Quận 4','type' => 'Quận','matp' => '79'),
            array('maqh' => '774','name' => 'Quận 5','type' => 'Quận','matp' => '79'),
            array('maqh' => '775','name' => 'Quận 6','type' => 'Quận','matp' => '79'),
            array('maqh' => '776','name' => 'Quận 8','type' => 'Quận','matp' => '79'),
            array('maqh' => '777','name' => 'Quận Bình Tân','type' => 'Quận','matp' => '79'),
            array('maqh' => '778','name' => 'Quận 7','type' => 'Quận','matp' => '79'),
            array('maqh' => '783','name' => 'Huyện Củ Chi','type' => 'Huyện','matp' => '79'),
            array('maqh' => '784','name' => 'Huyện Hóc Môn','type' => 'Huyện','matp' => '79'),
            array('maqh' => '785','name' => 'Huyện Bình Chánh','type' => 'Huyện','matp' => '79'),
            array('maqh' => '786','name' => 'Huyện Nhà Bè','type' => 'Huyện','matp' => '79'),
            array('maqh' => '787','name' => 'Huyện Cần Giờ','type' => 'Huyện','matp' => '79'),
            array('maqh' => '794','name' => 'Thành phố Tân An','type' => 'Thành phố','matp' => '80'),
            array('maqh' => '795','name' => 'Thị xã Kiến Tường','type' => 'Thị xã','matp' => '80'),
            array('maqh' => '796','name' => 'Huyện Tân Hưng','type' => 'Huyện','matp' => '80'),
            array('maqh' => '797','name' => 'Huyện Vĩnh Hưng','type' => 'Huyện','matp' => '80'),
            array('maqh' => '798','name' => 'Huyện Mộc Hóa','type' => 'Huyện','matp' => '80'),
            array('maqh' => '799','name' => 'Huyện Tân Thạnh','type' => 'Huyện','matp' => '80'),
            array('maqh' => '800','name' => 'Huyện Thạnh Hóa','type' => 'Huyện','matp' => '80'),
            array('maqh' => '801','name' => 'Huyện Đức Huệ','type' => 'Huyện','matp' => '80'),
            array('maqh' => '802','name' => 'Huyện Đức Hòa','type' => 'Huyện','matp' => '80'),
            array('maqh' => '803','name' => 'Huyện Bến Lức','type' => 'Huyện','matp' => '80'),
            array('maqh' => '804','name' => 'Huyện Thủ Thừa','type' => 'Huyện','matp' => '80'),
            array('maqh' => '805','name' => 'Huyện Tân Trụ','type' => 'Huyện','matp' => '80'),
            array('maqh' => '806','name' => 'Huyện Cần Đước','type' => 'Huyện','matp' => '80'),
            array('maqh' => '807','name' => 'Huyện Cần Giuộc','type' => 'Huyện','matp' => '80'),
            array('maqh' => '808','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '80'),
            array('maqh' => '815','name' => 'Thành phố Mỹ Tho','type' => 'Thành phố','matp' => '82'),
            array('maqh' => '816','name' => 'Thị xã Gò Công','type' => 'Thị xã','matp' => '82'),
            array('maqh' => '817','name' => 'Thị xã Cai Lậy','type' => 'Huyện','matp' => '82'),
            array('maqh' => '818','name' => 'Huyện Tân Phước','type' => 'Huyện','matp' => '82'),
            array('maqh' => '819','name' => 'Huyện Cái Bè','type' => 'Huyện','matp' => '82'),
            array('maqh' => '820','name' => 'Huyện Cai Lậy','type' => 'Thị xã','matp' => '82'),
            array('maqh' => '821','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '82'),
            array('maqh' => '822','name' => 'Huyện Chợ Gạo','type' => 'Huyện','matp' => '82'),
            array('maqh' => '823','name' => 'Huyện Gò Công Tây','type' => 'Huyện','matp' => '82'),
            array('maqh' => '824','name' => 'Huyện Gò Công Đông','type' => 'Huyện','matp' => '82'),
            array('maqh' => '825','name' => 'Huyện Tân Phú Đông','type' => 'Huyện','matp' => '82'),
            array('maqh' => '829','name' => 'Thành phố Bến Tre','type' => 'Thành phố','matp' => '83'),
            array('maqh' => '831','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '83'),
            array('maqh' => '832','name' => 'Huyện Chợ Lách','type' => 'Huyện','matp' => '83'),
            array('maqh' => '833','name' => 'Huyện Mỏ Cày Nam','type' => 'Huyện','matp' => '83'),
            array('maqh' => '834','name' => 'Huyện Giồng Trôm','type' => 'Huyện','matp' => '83'),
            array('maqh' => '835','name' => 'Huyện Bình Đại','type' => 'Huyện','matp' => '83'),
            array('maqh' => '836','name' => 'Huyện Ba Tri','type' => 'Huyện','matp' => '83'),
            array('maqh' => '837','name' => 'Huyện Thạnh Phú','type' => 'Huyện','matp' => '83'),
            array('maqh' => '838','name' => 'Huyện Mỏ Cày Bắc','type' => 'Huyện','matp' => '83'),
            array('maqh' => '842','name' => 'Thành phố Trà Vinh','type' => 'Thành phố','matp' => '84'),
            array('maqh' => '844','name' => 'Huyện Càng Long','type' => 'Huyện','matp' => '84'),
            array('maqh' => '845','name' => 'Huyện Cầu Kè','type' => 'Huyện','matp' => '84'),
            array('maqh' => '846','name' => 'Huyện Tiểu Cần','type' => 'Huyện','matp' => '84'),
            array('maqh' => '847','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '84'),
            array('maqh' => '848','name' => 'Huyện Cầu Ngang','type' => 'Huyện','matp' => '84'),
            array('maqh' => '849','name' => 'Huyện Trà Cú','type' => 'Huyện','matp' => '84'),
            array('maqh' => '850','name' => 'Huyện Duyên Hải','type' => 'Huyện','matp' => '84'),
            array('maqh' => '851','name' => 'Thị xã Duyên Hải','type' => 'Thị xã','matp' => '84'),
            array('maqh' => '855','name' => 'Thành phố Vĩnh Long','type' => 'Thành phố','matp' => '86'),
            array('maqh' => '857','name' => 'Huyện Long Hồ','type' => 'Huyện','matp' => '86'),
            array('maqh' => '858','name' => 'Huyện Mang Thít','type' => 'Huyện','matp' => '86'),
            array('maqh' => '859','name' => 'Huyện  Vũng Liêm','type' => 'Huyện','matp' => '86'),
            array('maqh' => '860','name' => 'Huyện Tam Bình','type' => 'Huyện','matp' => '86'),
            array('maqh' => '861','name' => 'Thị xã Bình Minh','type' => 'Thị xã','matp' => '86'),
            array('maqh' => '862','name' => 'Huyện Trà Ôn','type' => 'Huyện','matp' => '86'),
            array('maqh' => '863','name' => 'Huyện Bình Tân','type' => 'Huyện','matp' => '86'),
            array('maqh' => '866','name' => 'Thành phố Cao Lãnh','type' => 'Thành phố','matp' => '87'),
            array('maqh' => '867','name' => 'Thành phố Sa Đéc','type' => 'Thành phố','matp' => '87'),
            array('maqh' => '868','name' => 'Thị xã Hồng Ngự','type' => 'Thị xã','matp' => '87'),
            array('maqh' => '869','name' => 'Huyện Tân Hồng','type' => 'Huyện','matp' => '87'),
            array('maqh' => '870','name' => 'Huyện Hồng Ngự','type' => 'Huyện','matp' => '87'),
            array('maqh' => '871','name' => 'Huyện Tam Nông','type' => 'Huyện','matp' => '87'),
            array('maqh' => '872','name' => 'Huyện Tháp Mười','type' => 'Huyện','matp' => '87'),
            array('maqh' => '873','name' => 'Huyện Cao Lãnh','type' => 'Huyện','matp' => '87'),
            array('maqh' => '874','name' => 'Huyện Thanh Bình','type' => 'Huyện','matp' => '87'),
            array('maqh' => '875','name' => 'Huyện Lấp Vò','type' => 'Huyện','matp' => '87'),
            array('maqh' => '876','name' => 'Huyện Lai Vung','type' => 'Huyện','matp' => '87'),
            array('maqh' => '877','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '87'),
            array('maqh' => '883','name' => 'Thành phố Long Xuyên','type' => 'Thành phố','matp' => '89'),
            array('maqh' => '884','name' => 'Thành phố Châu Đốc','type' => 'Thành phố','matp' => '89'),
            array('maqh' => '886','name' => 'Huyện An Phú','type' => 'Huyện','matp' => '89'),
            array('maqh' => '887','name' => 'Thị xã Tân Châu','type' => 'Thị xã','matp' => '89'),
            array('maqh' => '888','name' => 'Huyện Phú Tân','type' => 'Huyện','matp' => '89'),
            array('maqh' => '889','name' => 'Huyện Châu Phú','type' => 'Huyện','matp' => '89'),
            array('maqh' => '890','name' => 'Huyện Tịnh Biên','type' => 'Huyện','matp' => '89'),
            array('maqh' => '891','name' => 'Huyện Tri Tôn','type' => 'Huyện','matp' => '89'),
            array('maqh' => '892','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '89'),
            array('maqh' => '893','name' => 'Huyện Chợ Mới','type' => 'Huyện','matp' => '89'),
            array('maqh' => '894','name' => 'Huyện Thoại Sơn','type' => 'Huyện','matp' => '89'),
            array('maqh' => '899','name' => 'Thành phố Rạch Giá','type' => 'Thành phố','matp' => '91'),
            array('maqh' => '900','name' => 'Thị xã Hà Tiên','type' => 'Thị xã','matp' => '91'),
            array('maqh' => '902','name' => 'Huyện Kiên Lương','type' => 'Huyện','matp' => '91'),
            array('maqh' => '903','name' => 'Huyện Hòn Đất','type' => 'Huyện','matp' => '91'),
            array('maqh' => '904','name' => 'Huyện Tân Hiệp','type' => 'Huyện','matp' => '91'),
            array('maqh' => '905','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '91'),
            array('maqh' => '906','name' => 'Huyện Giồng Riềng','type' => 'Huyện','matp' => '91'),
            array('maqh' => '907','name' => 'Huyện Gò Quao','type' => 'Huyện','matp' => '91'),
            array('maqh' => '908','name' => 'Huyện An Biên','type' => 'Huyện','matp' => '91'),
            array('maqh' => '909','name' => 'Huyện An Minh','type' => 'Huyện','matp' => '91'),
            array('maqh' => '910','name' => 'Huyện Vĩnh Thuận','type' => 'Huyện','matp' => '91'),
            array('maqh' => '911','name' => 'Huyện Phú Quốc','type' => 'Huyện','matp' => '91'),
            array('maqh' => '912','name' => 'Huyện Kiên Hải','type' => 'Huyện','matp' => '91'),
            array('maqh' => '913','name' => 'Huyện U Minh Thượng','type' => 'Huyện','matp' => '91'),
            array('maqh' => '914','name' => 'Huyện Giang Thành','type' => 'Huyện','matp' => '91'),
            array('maqh' => '916','name' => 'Quận Ninh Kiều','type' => 'Quận','matp' => '92'),
            array('maqh' => '917','name' => 'Quận Ô Môn','type' => 'Quận','matp' => '92'),
            array('maqh' => '918','name' => 'Quận Bình Thuỷ','type' => 'Quận','matp' => '92'),
            array('maqh' => '919','name' => 'Quận Cái Răng','type' => 'Quận','matp' => '92'),
            array('maqh' => '923','name' => 'Quận Thốt Nốt','type' => 'Quận','matp' => '92'),
            array('maqh' => '924','name' => 'Huyện Vĩnh Thạnh','type' => 'Huyện','matp' => '92'),
            array('maqh' => '925','name' => 'Huyện Cờ Đỏ','type' => 'Huyện','matp' => '92'),
            array('maqh' => '926','name' => 'Huyện Phong Điền','type' => 'Huyện','matp' => '92'),
            array('maqh' => '927','name' => 'Huyện Thới Lai','type' => 'Huyện','matp' => '92'),
            array('maqh' => '930','name' => 'Thành phố Vị Thanh','type' => 'Thành phố','matp' => '93'),
            array('maqh' => '931','name' => 'Thị xã Ngã Bảy','type' => 'Thị xã','matp' => '93'),
            array('maqh' => '932','name' => 'Huyện Châu Thành A','type' => 'Huyện','matp' => '93'),
            array('maqh' => '933','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '93'),
            array('maqh' => '934','name' => 'Huyện Phụng Hiệp','type' => 'Huyện','matp' => '93'),
            array('maqh' => '935','name' => 'Huyện Vị Thuỷ','type' => 'Huyện','matp' => '93'),
            array('maqh' => '936','name' => 'Huyện Long Mỹ','type' => 'Huyện','matp' => '93'),
            array('maqh' => '937','name' => 'Thị xã Long Mỹ','type' => 'Thị xã','matp' => '93'),
            array('maqh' => '941','name' => 'Thành phố Sóc Trăng','type' => 'Thành phố','matp' => '94'),
            array('maqh' => '942','name' => 'Huyện Châu Thành','type' => 'Huyện','matp' => '94'),
            array('maqh' => '943','name' => 'Huyện Kế Sách','type' => 'Huyện','matp' => '94'),
            array('maqh' => '944','name' => 'Huyện Mỹ Tú','type' => 'Huyện','matp' => '94'),
            array('maqh' => '945','name' => 'Huyện Cù Lao Dung','type' => 'Huyện','matp' => '94'),
            array('maqh' => '946','name' => 'Huyện Long Phú','type' => 'Huyện','matp' => '94'),
            array('maqh' => '947','name' => 'Huyện Mỹ Xuyên','type' => 'Huyện','matp' => '94'),
            array('maqh' => '948','name' => 'Thị xã Ngã Năm','type' => 'Thị xã','matp' => '94'),
            array('maqh' => '949','name' => 'Huyện Thạnh Trị','type' => 'Huyện','matp' => '94'),
            array('maqh' => '950','name' => 'Thị xã Vĩnh Châu','type' => 'Thị xã','matp' => '94'),
            array('maqh' => '951','name' => 'Huyện Trần Đề','type' => 'Huyện','matp' => '94'),
            array('maqh' => '954','name' => 'Thành phố Bạc Liêu','type' => 'Thành phố','matp' => '95'),
            array('maqh' => '956','name' => 'Huyện Hồng Dân','type' => 'Huyện','matp' => '95'),
            array('maqh' => '957','name' => 'Huyện Phước Long','type' => 'Huyện','matp' => '95'),
            array('maqh' => '958','name' => 'Huyện Vĩnh Lợi','type' => 'Huyện','matp' => '95'),
            array('maqh' => '959','name' => 'Thị xã Giá Rai','type' => 'Thị xã','matp' => '95'),
            array('maqh' => '960','name' => 'Huyện Đông Hải','type' => 'Huyện','matp' => '95'),
            array('maqh' => '961','name' => 'Huyện Hoà Bình','type' => 'Huyện','matp' => '95'),
            array('maqh' => '964','name' => 'Thành phố Cà Mau','type' => 'Thành phố','matp' => '96'),
            array('maqh' => '966','name' => 'Huyện U Minh','type' => 'Huyện','matp' => '96'),
            array('maqh' => '967','name' => 'Huyện Thới Bình','type' => 'Huyện','matp' => '96'),
            array('maqh' => '968','name' => 'Huyện Trần Văn Thời','type' => 'Huyện','matp' => '96'),
            array('maqh' => '969','name' => 'Huyện Cái Nước','type' => 'Huyện','matp' => '96'),
            array('maqh' => '970','name' => 'Huyện Đầm Dơi','type' => 'Huyện','matp' => '96'),
            array('maqh' => '971','name' => 'Huyện Năm Căn','type' => 'Huyện','matp' => '96'),
            array('maqh' => '972','name' => 'Huyện Phú Tân','type' => 'Huyện','matp' => '96'),
            array('maqh' => '973','name' => 'Huyện Ngọc Hiển','type' => 'Huyện','matp' => '96')
        );

        foreach($quanhuyen as $quan)
        {
            DB::table('quanhuyen')->insert([
            'maqh' => $quan['maqh'],
            'name' => $quan['name'],
            'type' => $quan['type'],
            'matp'=> $quan['matp'],
            ]);
        }
    }
}
